<a href="https://colab.research.google.com/github/diego-gutierrez10/diego-gutierrez10/blob/main/AI_ML_Challenge_Diego_Gutierrez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Made by undergraduate student Diego Gutierrez for AI Planet Data Science Bootcamp**

Universidad Autónoma de Baja California

Ensenada, Baja California, México

In [ ]:
#We import the libraries needed and create a dataframe from the given CSV

import pandas as pd
import numpy as np
pharma_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')

In [ ]:
#We portray the head of the Dataframe to get an idea of how the values are like

pharma_data.head()

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Treated_with_drugs,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,B,C,D,E,F,Z,Number_of_prev_cond,Survived_1_year
0,22374,8,3333,DX6,56,18.479385,YES,URBAN,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,0
1,18164,5,5740,DX2,36,22.945566,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,6283,23,10446,DX6,48,27.510027,YES,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0
3,5339,51,12011,DX1,5,19.130976,NO,URBAN,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
4,33012,0,12513,NaN,128,1.348400,Cannot say,RURAL,Stable,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1

In [ ]:
#For an easier processing of the model we drop the rows with empty values (NaN)

#pharma_data.isnull().sum()
pharma_data = pharma_data.dropna(axis=0)

In [ ]:
#We portray the description of the Dataframe to get an idea of the values that we are working with

#pharma_data.columns
pharma_data.describe()

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Patient_Age,Patient_Body_Mass_Index,A,B,C,D,E,F,Z,Number_of_prev_cond,Survived_1_year
count,21849.000000,21849.000000,21849.000000,21849.000000,21849.000000,21849.000000,21849.000000,21849.000000,21849.000000,21849.000000,21849.000000,21849.0,21849.000000,21849.000000
mean,16516.195066,26.399469,6252.329214,33.232230,23.453391,0.898439,0.136436,0.185180,0.083665,0.393473,0.053732,0.0,1.750927,0.624376
std,9533.314321,15.025344,3599.188973,19.406999,3.774410,0.302077,0.343259,0.388452,0.276891,0.488531,0.225494,0.0,0.770323,0.484295
min,2.000000,1.000000,1.000000,0.000000,17.000336,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000
25%,8232.000000,13.000000,3167.000000,16.000000,20.205050,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,1.000000,0.000000
50%,16577.000000,26.000000,6224.000000,33.000000,23.368735,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,2.000000,1.000000
75%,24798.000000,39.000000,9377.000000,50.000000,26.775992,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,2.000000,1.000000
max,32982.000000,52.000000,12500.000000,66.000000,29.999579,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.0,5.000000,1.000000

In [ ]:
#We make dummies (aka 'One-hot econding') for the non-numerical values

pharma_data = pd.get_dummies(pharma_data, prefix_sep='_', drop_first=True)
pharma_data.columns

Index(['ID_Patient_Care_Situation', 'Diagnosed_Condition', 'Patient_ID',
       'Patient_Age', 'Patient_Body_Mass_Index', 'A', 'B', 'C', 'D', 'E', 'F',
       'Z', 'Number_of_prev_cond', 'Survived_1_year',
       'Treated_with_drugs_DX1 DX2 ', 'Treated_with_drugs_DX1 DX2 DX3 ',
       'Treated_with_drugs_DX1 DX2 DX3 DX4 ',
       'Treated_with_drugs_DX1 DX2 DX3 DX4 DX5 ',
       'Treated_with_drugs_DX1 DX2 DX3 DX5 ',
       'Treated_with_drugs_DX1 DX2 DX4 ',
       'Treated_with_drugs_DX1 DX2 DX4 DX5 ',
       'Treated_with_drugs_DX1 DX2 DX5 ', 'Treated_with_drugs_DX1 DX3 ',
       'Treated_with_drugs_DX1 DX3 DX4 ',
       'Treated_with_drugs_DX1 DX3 DX4 DX5 ',
       'Treated_with_drugs_DX1 DX3 DX5 ', 'Treated_with_drugs_DX1 DX4 ',
       'Treated_with_drugs_DX1 DX4 DX5 ', 'Treated_with_drugs_DX1 DX5 ',
       'Treated_with_drugs_DX2 ', 'Treated_with_drugs_DX2 DX3 ',
       'Treated_with_drugs_DX2 DX3 DX4 ',
       'Treated_with_drugs_DX2 DX3 DX4 DX5 ',
       'Treated_with_drugs_DX2 DX3 DX5 ', 'Treated_with_drugs_DX2 DX4 ',
       'Treated_with_drugs_DX2 DX4 DX5 ', 'Treated_with_drugs_DX2 DX5 ',
       'Treated_with_drugs_DX3 ', 'Treated_with_drugs_DX3 DX4 ',
       'Treated_with_drugs_DX3 DX4 DX5 ', 'Treated_with_drugs_DX3 DX5 ',
       'Treated_with_drugs_DX4 ', 'Treated_with_drugs_DX4 DX5 ',
       'Treated_with_drugs_DX5 ', 'Treated_with_drugs_DX6',
       'Patient_Smoker_YES', 'Patient_Rural_Urban_URBAN'],
      dtype='object')

In [ ]:
#We separate our "X" (What the model will learn from) and "Y"(The prediction target)

X = pharma_data.drop('Survived_1_year', axis = 1)
y = pharma_data.Survived_1_year

# **ML Model making:**

In [ ]:
#We import the machine learning library (scikit-learn), and split our "X" and "y" by 2/3 for the model training and 1/3 for the model testing

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=66)

x_train.head()
y_train.head()

22561    0
18521    1
14450    1
16198    1
2185     1
Name: Survived_1_year, dtype: int64

In [ ]:
#We check that there's no missing values left

x_train.isnull().sum()

ID_Patient_Care_Situation                  0
Diagnosed_Condition                        0
Patient_ID                                 0
Patient_Age                                0
Patient_Body_Mass_Index                    0
A                                          0
B                                          0
C                                          0
D                                          0
E                                          0
F                                          0
Z                                          0
Number_of_prev_cond                        0
Treated_with_drugs_DX1 DX2                 0
Treated_with_drugs_DX1 DX2 DX3             0
Treated_with_drugs_DX1 DX2 DX3 DX4         0
Treated_with_drugs_DX1 DX2 DX3 DX4 DX5     0
Treated_with_drugs_DX1 DX2 DX3 DX5         0
Treated_with_drugs_DX1 DX2 DX4             0
Treated_with_drugs_DX1 DX2 DX4 DX5         0
Treated_with_drugs_DX1 DX2 DX5             0
Treated_with_drugs_DX1 DX3                 0
Treated_with_drugs_DX1 DX3 DX4             0
Treated_with_drugs_DX1 DX3 DX4 DX5         0
Treated_with_drugs_DX1 DX3 DX5             0
Treated_with_drugs_DX1 DX4                 0
Treated_with_drugs_DX1 DX4 DX5             0
Treated_with_drugs_DX1 DX5                 0
Treated_with_drugs_DX2                     0
Treated_with_drugs_DX2 DX3                 0
Treated_with_drugs_DX2 DX3 DX4             0
Treated_with_drugs_DX2 DX3 DX4 DX5         0
Treated_with_drugs_DX2 DX3 DX5             0
Treated_with_drugs_DX2 DX4                 0
Treated_with_drugs_DX2 DX4 DX5             0
Treated_with_drugs_DX2 DX5                 0
Treated_with_drugs_DX3                     0
Treated_with_drugs_DX3 DX4                 0
Treated_with_drugs_DX3 DX4 DX5             0
Treated_with_drugs_DX3 DX5                 0
Treated_with_drugs_DX4                     0
Treated_with_drugs_DX4 DX5                 0
Treated_with_drugs_DX5                     0
Treated_with_drugs_DX6                     0
Patient_Smoker_YES                         0
Patient_Rural_Urban_URBAN                  0
dtype: int64

In [ ]:
#As the model target is a 'Yes or No' answer, we will use DecisionTreeClassifier: We import it and fit the model with the training X and y
from sklearn.tree import DecisionTreeClassifier

pharma_model = DecisionTreeClassifier(random_state=66, max_depth=7, min_samples_split=4)
pharma_model.fit(x_train, y_train)
print(pharma_model.predict(x_train.head(50)))
print(y_train.head(50))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 0 1 0
 1 1 0 1 0 1 1 0 1 0 1 1 0]
22561    0
18521    1
14450    1
16198    1
2185     1
9869     1
9697     1
1361     1
21312    1
13359    1
3354     1
14476    1
18098    1
7853     1
9772     0
11034    1
14298    1
5223     0
2181     0
17047    1
2206     1
20773    1
4983     0
9727     1
15212    0
12344    1
3779     1
5481     1
6702     1
21744    1
14365    1
15214    1
13345    1
18198    0
18239    1
13335    0
4792     0
5603     1
6232     1
2298     0
1869     1
17380    0
5187     1
21251    1
21600    0
9248     1
3304     0
11886    1
4738     1
3656     0
Name: Survived_1_year, dtype: int64

## We have now finshed making the model that allows us to predict if a patient will survive or not.

## Finally, we need to test it on the unseen third of the data or "x_test"

In [ ]:
from sklearn.metrics import accuracy_score
print('Training accuracy:',accuracy_score(y_train, pharma_model.predict(x_train)))
print('Test accuracy:', accuracy_score(y_test, pharma_model.predict(x_test)))

Training accuracy: 0.8049561919707074
Test accuracy: 0.7824561403508772

In [ ]:
#We make an array for the predictions of our model over x_test

y_true = pharma_model.predict(x_test)

In [ ]:
#We check what we get on the f1_score

from sklearn.metrics import f1_score

print('The f1_score is',f1_score(y_test, y_true))

The f1_score is 0.8352968352968353

## **Now that we have finished making and evaluating or ML model, we will make the final prediction for the submission on the challenge**

In [ ]:
#We import the CSV and make a dataframe for it

test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')

In [ ]:
#We take a look to the values present in the test_data Dataframe

test_data.head()

,ID_Patient_Care_Situation,Diagnosed_Condition,Patient_ID,Treated_with_drugs,Patient_Age,Patient_Body_Mass_Index,Patient_Smoker,Patient_Rural_Urban,Patient_mental_condition,A,B,C,D,E,F,Z,Number_of_prev_cond
0,19150,40,3709,DX3,16,29.443894,NO,RURAL,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
1,23216,52,986,DX6,24,26.836321,NO,URBAN,Stable,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
2,11890,50,11821,DX4 DX5,63,25.523280,NO,RURAL,Stable,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
3,7149,32,3292,DX6,42,27.171155,NO,URBAN,Stable,1.0,0.0,1.0,0.0,1.0,0.0,0.0,3.0
4,22845,20,9959,DX3,50,25.556192,NO,RURAL,Stable,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
#We check that tere's no missing values in the test_data Dataframe


test_data.isnull().sum()

ID_Patient_Care_Situation    0
Diagnosed_Condition          0
Patient_ID                   0
Treated_with_drugs           0
Patient_Age                  0
Patient_Body_Mass_Index      0
Patient_Smoker               0
Patient_Rural_Urban          0
Patient_mental_condition     0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Number_of_prev_cond          0
dtype: int64

In [ ]:
#We make dummies as the ones in the pharma_data Dataframe

test_data = pd.get_dummies(test_data, prefix_sep='_', drop_first=True)
test_data.columns

Index(['ID_Patient_Care_Situation', 'Diagnosed_Condition', 'Patient_ID',
       'Patient_Age', 'Patient_Body_Mass_Index', 'A', 'B', 'C', 'D', 'E', 'F',
       'Z', 'Number_of_prev_cond', 'Treated_with_drugs_DX1 DX2 ',
       'Treated_with_drugs_DX1 DX2 DX3 ',
       'Treated_with_drugs_DX1 DX2 DX3 DX4 ',
       'Treated_with_drugs_DX1 DX2 DX3 DX4 DX5 ',
       'Treated_with_drugs_DX1 DX2 DX3 DX5 ',
       'Treated_with_drugs_DX1 DX2 DX4 ',
       'Treated_with_drugs_DX1 DX2 DX4 DX5 ',
       'Treated_with_drugs_DX1 DX2 DX5 ', 'Treated_with_drugs_DX1 DX3 ',
       'Treated_with_drugs_DX1 DX3 DX4 ',
       'Treated_with_drugs_DX1 DX3 DX4 DX5 ',
       'Treated_with_drugs_DX1 DX3 DX5 ', 'Treated_with_drugs_DX1 DX4 ',
       'Treated_with_drugs_DX1 DX4 DX5 ', 'Treated_with_drugs_DX1 DX5 ',
       'Treated_with_drugs_DX2 ', 'Treated_with_drugs_DX2 DX3 ',
       'Treated_with_drugs_DX2 DX3 DX4 ',
       'Treated_with_drugs_DX2 DX3 DX4 DX5 ',
       'Treated_with_drugs_DX2 DX3 DX5 ', 'Treated_with_drugs_DX2 DX4 ',
       'Treated_with_drugs_DX2 DX4 DX5 ', 'Treated_with_drugs_DX2 DX5 ',
       'Treated_with_drugs_DX3 ', 'Treated_with_drugs_DX3 DX4 ',
       'Treated_with_drugs_DX3 DX4 DX5 ', 'Treated_with_drugs_DX3 DX5 ',
       'Treated_with_drugs_DX4 ', 'Treated_with_drugs_DX4 DX5 ',
       'Treated_with_drugs_DX5 ', 'Treated_with_drugs_DX6',
       'Patient_Smoker_YES', 'Patient_Rural_Urban_URBAN'],
      dtype='object')

In [ ]:
#We make another dataframe (prediction_CSV) for the pharma_model predictions based on test_data

prediction_CSV = pd.DataFrame((pharma_model.predict(test_data)), columns=['prediction'])
prediction_CSV.head()

   prediction
0           1
1           1
2           1
3           0
4           1

In [ ]:
#Finally we export the new dataframe to our drive

prediction_CSV.to_csv('predictions_grandfinal.csv', index=False)
!cp predictions_grandfinal.csv "drive/My Drive/ML Challenge/"

#That's all for the moment, thank you for your attention!
diego.gutierrez10@uabc.edu.mx